name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup pandoc
      uses: nikeee/setup-pandoc@master

    - name: build site
      run: make -B

    - name: Run check
      run: make check

    - name: Run distcheck
      run: make distcheck
