name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup pandoc
      uses: nikeee/setup-pandoc@master

    - name: build site
      run: make -B

    - name: Verify produced_pages directory
      run: |
        if [ -z "$(ls -A produced_pages)" ]; then
          echo "The produced_pages directory is empty. Deployment failed."
          exit 1
        else
          echo "The produced_pages directory contains files. Deployment check passed."
        fi

    - name: Run check
      run: make check

    - name: Run distcheck
      run: make distcheck